package ar.edu.utn.frc.tup.piii.engine.event;

public enum GameEventType {
    CARD_DRAWN,
    VICTORY_DECIDED,
    POKEMON_PLACED_ON_BENCH,
    ENERGY_ATTACHED,
    POKEMON_EVOLVED,
    TRAINER_PLAYED,
    RETREAT_EXECUTED,
    DAMAGE_APPLIED,
    KNOCKOUT_OCCURRED,
    ATTACK_DECLARED,
    PHASE_CHANGED,
    STATE_UPDATED,
    PRIZE_TAKEN,
    MULLIGAN_REVEALED
}
